modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MoriyaShiine/wendigoism/issues"
[[mods]]
modId="wendigoism"
version="${file.jarVersion}"
displayName="Wendigoism"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wendigoism"
logoFile="icon.png"
authors="MoriyaShiine, cybercat5555"
description='''A remake of the original Cannibalism mod'''
[[dependencies.wendigoism]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wendigoism]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"