modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/MoriyaShiine/cannibalism/issues" #optional
[[mods]] #mandatory
modId="wendigoism" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Wendigoism" #mandatory
displayURL="http://example.com/" #optional
authors="MoriyaShiine, cybercat5555, sorazodia" #optional
description='''
A remake of the original Cannibalism mod
'''
[[dependencies.wendigoism]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.wendigoism]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
